### ISSUE TITLE
mGear: curve.update_curve_from_file Issue

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear_core#10]
_From @Daelex on August 6, 2018 7:42_

Hi Miquel.

There's an issue with the control curves I/O. The exporter works fine but the importer break curves shapes connexions, and let Maya deletes some nodes, so it deeply break the rig.
Here is a simple snippet we use in our customSteps as a workaround.

```python
import pymel.core as pm
import mgear.maya.curve

# Gather shapes connexions
temp_nodes = list()
ctrls = [i for i in pm.ls(dag=True) if i.name().endswith('ctl')]
shapes_inputs = list()
for ctrl in ctrls:
    shapes = ctrl.getShapes()
    for shape in shapes:
        inputs = shape.v.inputs(plugs=True)
        if inputs:
            connexion = (inputs[0].name(), shape.v.name())
            shapes_inputs.append(connexion)
            # Make a temp connexion to avoid maya to delete unused nodes
            node = pm.createNode('transform')
            temp_nodes.append(node)
            inputs[0].connect(node.v)
            
mgear.maya.curve.update_curve_from_file()

for attr in shapes_inputs:
    pm.connectAttr(attr[0], attr[1], force=True)
pm.delete(temp_nodes)
```

_Copied from original issue: mgear-dev/mgear#237_

**Comment by miquelcampos** [comment]
Hi @Daelex 

Thanks for the feedback and sorry for the late reply. (literally, I had open the tab 2 days in chrome :P )

I will check this ASAP and probably use your snippet. Thanks!

**Comment by miquelcampos** [comment]
Hello @Daelex

Have been long time since the issue was reported, sorry.
I am checking the Curves I/O today.
What kind of inputs do you have in the curves shapes?  

The IO doesn't handle any inputs, just delete the old shape by replacing by a new one.

Thanks,
Miquel

**Comment by alexedde** [comment]
Hey Miquel,

I think it was shape visibility. I took care of visibility only but in somes cases it could be something else like shape color. Maybe we need a more global solution to handle this issue.

Thanks,
Alex

**Comment by miquelcampos** [comment]
Hi @Daelex 

Thanks again for the info.

**Comment by miquelcampos** [comment]
@Daelex  I think with this should handle any input  connection to any attribute.  :D 

The only limitation is that we only handle the connections of the first shape and apply it to the new shapes.
Basically this is a design decision to handle different numbers of shape. For example if the control have only one and we replace by 3 shapes. (i.e sphere Icon has 3 shapes) or the other way, if we have 3 shapes and replace by only one shape.

Thanks again for the feedback!
