### ISSUE TITLE
mGear: skin: exportSkinPack always brings up dialogue

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear_core#4]
_From @RafaelVillar on March 20, 2018 10:2_

exportSkinPack: The dialogue is always brought up when ran, unlike the other export options that only do so when a path is not provided.

Other suggestions, this function should be broken up into two. One that only accepts a path, and another that brings up the dialogue and a start path for dialogue box.

_Copied from original issue: mgear-dev/mgear#179_

**Comment by RafaelVillar** [comment]
@miquelcampos I think this is good to merge in. If you want.
