### ISSUE TITLE
After a build is done, the new animation context menu of MGear 3.4 is not working and Maya viewport heads up display are gone

### ISSUE THREAD

**Issue by nestorcolt** [mgear-dev/mgear_core#46]
After any build the heads up display are gone from the viewport, and is impossible to bring them back. Just closing Maya and re open it will solve it.

The new feature of MGear 3.4 context menu isn't working either after a build has been done. I need to uncheck Mgear viewport menu and check it again to make it work

**To Reproduce**
Make a build

**Screenshots**
![mGear_viewport_bug](https://user-images.githubusercontent.com/31187725/74843774-b3e4bc80-532c-11ea-9702-172267c7e74f.png)

**Comment by miquelcampos** [comment]
Just moved the issue under mgear_core :)

**Comment by jdrese** [comment]
Hello @nestorcolt 
I am not able to reproduce this error. Please let me know what Maya version you are running and what type of Maya config you are running in terms of Maya modules or plugins.

**Comment by jdrese** [comment]
Closing this because can't reproduce and did not get any more comments from Nestor
