### ISSUE TITLE
Compiled UI files require manual edits

### ISSUE THREAD

**Issue by Ruuttu** [mgear-dev/mgear_core#57]
All UIs in mGear import Qt like so: 
`import mgear.core.pyqt as pyqt`

When I build a UI using the "Compile PyQt ui" option, the resulting file does imports like this instead:
`from PySide2 import QtCore, QtGui, QtWidgets`

I assume the python file should be manually edited after compilation to bring it in line with other UIs? The generated python is so consistent I think it would be possible for mGear to fix it automatically after compilation.

**Comment by miquelcampos** [comment]
Hello @Ruuttu  
sorry for the late reply. 
Yes for the moment it is needed to update this manually. 
Probably in the future, we will stop using qtDesigner and .ui files. So I am not sure if is worth to invest time to avoid manual edits

**Comment by Ruuttu** [comment]
Aha. Would the replacement be automatically generated UIs for parameters? Or plain written UI code?
But anyway, makes sense.
