### ISSUE TITLE
components path is repeatedly add to sys.path

### ISSUE THREAD

**Issue by akiwoRM** [mgear-dev/mgear_core#59]
Hi, there.

When running Guide Manager, shifter classic components path and the path defined by MGEAR_CUSTOM_COMPONENT_PATH variable are repeatedly added to sys.path.

Maybe, it should update importFromStandardOrCustomDirectories function in mgear.core.utils.
If it always exists in sys.path, ignore to the additions.

**Comment by miquelcampos** [comment]
this was fixed time ago here https://github.com/mgear-dev/mgear_core/issues/69
