### ISSUE TITLE
dag menu: make it work with control custom names

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear_core#62]
With custom names in controls, the right menu tools will not work. 

Also related: anim_utils: get_ik_fk_controls assumes that the component in the guide will have the same name as the component type #61

Probably custom names also affect synoptic and animPicker. Check after close this.

@jdrese I will work on this ticket this week.  Please let me know if it is ok with you. :)

**Comment by jdrese** [comment]
@miquelcampos yes no problem for me.

**Comment by miquelcampos** [comment]
Now is working with custom names in the components using "_" sign. (that was fixed on #61 ) 
But still not working with custom name rules.  Provably we need to implement a message connections system or another type of metadata in order to find the current blend attribute.

@jdrese  I am going to leave this bug open as a known issue. And will review it after finishing this project.   Any idea is welcome :)
I have moved the ticket to  3.x.x project

**Comment by miquelcampos** [comment]
@jdrese Changed my mind!
I think I have a solution but will need to add a few changes and test how it will affect other tools. 
Also need to keep the old method for back compatibility.

1. The name of the attribute should be related to the component name, not the component type name. For example, if the arm component is  called "brazo" the attributes will be also prefixed with "brazo_" and not "arm_"

2. add a few attributes from the component build that creates the ik and fk list of controls. So we can feed any name pattern

- component name + fk_match: i.e: brazo_custom_name_blabla_fk_match
- component name + ik_match: i.e: brazo_custom_name_blabla_ik_match

This will allow supporting multiple components of the same type on the same UI host

**Comment by jdrese** [comment]
This sounds indeed a better option!

**Comment by miquelcampos** [comment]
- [x] review behavior with ik/fk match in range
- [x] need add tag role attributes for controls. Related with https://github.com/mgear-dev/shifter_classic_components/issues/83
- [x] ik/fk controls _mth node needs to be handle with custom template names
- [x] Space switch is also affected
