### ISSUE TITLE
Add support for drag n drop of mGear filetypes, .sgt

### ISSUE THREAD

**Issue by RafaelVillar** [mgear-dev/mgear_core#79]
Adding support for drag and drop of filetypes used by mGear. Starting with guide files, .sgt.

This can be expanded on in the future for other mgear supported files. 

![mgear_menu_v0002](https://user-images.githubusercontent.com/7085330/109102225-bc57aa80-776b-11eb-96aa-611a2b54ef31.gif)

The initial location for the option has been placed here
![image](https://user-images.githubusercontent.com/7085330/109102358-0b054480-776c-11eb-9f2f-7af510f7d014.png)

This can be changed in the future, pending feedback. 

This will need to be tested thoroughly, as there is no way to predict every studio environment and installation.

**Comment by jdrese** [comment]
This is so cool @RafaelVillar

**Comment by RafaelVillar** [comment]
I am glad you like it. Credit goes to @miquelcampos for the idea.
